name: âš¡ Test Runner
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - "**"
    tags:
      - "*"
permissions:
  contents: write
jobs:
  setup:
    name: "ğŸ”§ Setup"
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Check out repo
        uses: actions/checkout@v4
      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"
          # cache-dependency-path: "package-lock.json"
      - name: ğŸ§¹ Clean install for cross-platform compatibility
        run: |
          npm ci --legacy-peer-deps
  test:
    name: ğŸƒ Test
    needs: setup
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Check out repo
        uses: actions/checkout@v4
      - name: â” Setup node (reuse cache from setup)
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"
      - name: Hydrate npm module cache
        uses: actions/cache@v3
        id: hydrate
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.hydrate.outputs.cache-hit != 'true'
        run: npm ci --legacy-peer-deps
      - name: ğŸ§ª Run Tests
        run: npm run test:ci
      - run: |
          ls -lath
          find tmp
      # Generate coverage badge from vitest coverage report.
      # https://github.com/marketplace/actions/vitest-badge-action
      - name: âš™ï¸ Generating coverage badges
        uses: jpb06/coverage-badges-action@v1.3.2
        with:
          branches: "*"
          badges-labels-prefix: "Test Coverage"
          badges-icon: vitest
          coverage-summary-path: tmp/coverage/coverage-summary.json
          output-folder: docs/assets
      - name: â¬†ï¸ Push badges branch
        run: git push origin badges
