name: âš¡ Test Runner
on:
  workflow_dispatch:
  workflow_call:
permissions:
  contents: write
jobs:
  setup:
    name: "ğŸ”§ Setup"
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: â¬‡ï¸ Check out repo
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: â” Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: "package.json"
          cache: "npm"
          # cache-dependency-path: "package-lock.json"
      - name: ğŸ§¹ Clean install for cross-platform compatibility
        run: |
          npm ci --legacy-peer-deps
  test:
    name: ğŸƒ Test
    needs: setup
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: â¬‡ï¸ Check out repo
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: â” Setup node (reuse cache from setup)
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: "package.json"
          cache: "npm"
      - name: Hydrate npm module cache
        uses: actions/cache@2f8e54208210a422b2efd51efaa6bd6d7ca8920f # v3.4.3
        id: hydrate
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.hydrate.outputs.cache-hit != 'true'
        run: npm ci --legacy-peer-deps
      - name: ğŸ§ª Run Tests
        run: npm run test:ci
      - name: âš™ï¸ Generating coverage badges
        run: |
          npx --yes coverage-badges-cli \
              --source tmp/coverage/coverage-summary.json \
              --style plastic \
              --type statements \
              --iconWidth 190 \
              --label "Test Coverage"  \
              --output docs/assets/coverage-badge.svg
      - name: â¬†ï¸ Push badges branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add docs/assets/coverage-badge.svg
          git commit -m "chore: update coverage badge"
          git push
