name: âš¡ Test Runner
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - "**"
    tags:
      - "*"
permissions:
  contents: write
jobs:
  setup:
    name: "ğŸ”§ Setup"
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Check out repo
        uses: actions/checkout@v4
      - name: â” Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"
          cache-dependency-path: "package-lock.json"
      - name: ğŸ“¥ Install Node.js dependencies
        run: npm install --legacy-peer-deps
      - run: npm list
  test:
    name: ğŸƒ Test
    needs: setup
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Check out repo
        uses: actions/checkout@v4
      - name: â” Setup node (reuse cache from setup)
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"
          cache-dependency-path: "package-lock.json"
          registry-url: "https://registry.npmjs.org"
      - run: npm list

      - name: ğŸ” Run Tests
        run: npm run test:ci
      # Generate coverage badge from vitest coverage report.
      # https://github.com/marketplace/actions/vitest-badge-action
      - name: âš™ï¸ Generating coverage badges
        uses: jpb06/coverage-badges-action@latest
        with:
          branches: "*"
          badges-icon: vitest
      - name: â¬†ï¸ Push badges branch
        run: git push origin badges
